"""empty message

Revision ID: 5547f373f613
Revises: dd585765edc1
Create Date: 2019-07-10 20:00:09.363890

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5547f373f613'
down_revision = 'dd585765edc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pictures', 'work_id',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pictures', 'work_id',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=20),
               nullable=False)
    # ### end Alembic commands ###
