"""empty message

Revision ID: c4c131f2d8cf
Revises: 2828aa81434a
Create Date: 2019-07-11 09:48:51.295504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4c131f2d8cf'
down_revision = '2828aa81434a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pictures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gray0', sa.String(length=20), nullable=False),
    sa.Column('gray1', sa.String(length=20), nullable=False),
    sa.Column('gray2', sa.String(length=20), nullable=False),
    sa.Column('gray3', sa.String(length=20), nullable=False),
    sa.Column('gray4', sa.String(length=20), nullable=False),
    sa.Column('gray5', sa.String(length=20), nullable=False),
    sa.Column('gray6', sa.String(length=20), nullable=False),
    sa.Column('gray7', sa.String(length=20), nullable=False),
    sa.Column('gray8', sa.String(length=20), nullable=False),
    sa.Column('gray9', sa.String(length=20), nullable=False),
    sa.Column('path', sa.String(length=50), nullable=False),
    sa.Column('time', sa.String(length=30), nullable=True),
    sa.Column('work_id', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pictures')
    # ### end Alembic commands ###
