"""empty message

Revision ID: dd585765edc1
Revises: 
Create Date: 2019-07-10 17:04:37.258426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd585765edc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pictures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gray0', sa.String(length=20), nullable=False),
    sa.Column('gray1', sa.String(length=20), nullable=False),
    sa.Column('gray2', sa.String(length=20), nullable=False),
    sa.Column('gray3', sa.String(length=20), nullable=False),
    sa.Column('gray4', sa.String(length=20), nullable=False),
    sa.Column('gray5', sa.String(length=20), nullable=False),
    sa.Column('gray6', sa.String(length=20), nullable=False),
    sa.Column('gray7', sa.String(length=20), nullable=False),
    sa.Column('gray8', sa.String(length=20), nullable=False),
    sa.Column('gray9', sa.String(length=20), nullable=False),
    sa.Column('path', sa.String(length=50), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('work_id', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pictures')
    # ### end Alembic commands ###
