# Generated by Django 2.1.3 on 2019-07-17 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinfo',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='heroinfo',
            name='is_delete',
        ),
    ]
