# Generated by Django 2.1.3 on 2019-07-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_auto_20190717_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='heroinfo',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
