"""empty message

Revision ID: 1eb49e5277f8
Revises: 8cf49735b038
Create Date: 2019-03-13 10:29:52.082011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eb49e5277f8'
down_revision = '8cf49735b038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('is_valid', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('img', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'img')
    op.drop_column('comment', 'is_valid')
    # ### end Alembic commands ###
