"""empty message

Revision ID: 9f408706d935
Revises: 375c3e046f48
Create Date: 2019-03-12 18:39:47.066695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f408706d935'
down_revision = '375c3e046f48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('question', 'is_valid',
               existing_type=mysql.TINYINT(display_width=4),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'is_valid',
               existing_type=mysql.TINYINT(display_width=4),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.drop_table('comment')
    # ### end Alembic commands ###
